### ISSUE TITLE
Firestore has already been initialized. You can only call settings() once, and only before calling any other methods on a Firestore object.

### ISSUE THREAD

**Issue by GorvGoyl** [gladly-team/next-firebase-auth#217] opened 2021-06-22 14:04 UTC
I'm trying to modify settings of firestore object in next.js api route but frequently face the below error:

`api/user.ts`:
```
import initAuth from "@/lib/initAuth";
import * as fireorm from "fireorm";
import { Collection, getRepository } from "fireorm";
import type { NextApiRequest, NextApiResponse } from "next";
import { getFirebaseAdmin } from "next-firebase-auth";

const db = getFirebaseAdmin().firestore();

 db.settings({
    host: "localhost:8080",
    ssl: false,
  });

fireorm.initialize(db);

initAuth();

```

Error:
```
Error: Firestore has already been initialized. You can only call settings() once, and only before calling any other methods on a Firestore object.
    at Firestore.settings (C:\Users\1gour\OneDrive\Documents\proj\node_modules\@google-cloud\firestore\build\src\index.js:442:19)
```

Sometimes it works sometime it throws error. Am I doing it wrong?

**Comment by kmjennison** [comment] 2021-06-27 21:21
Duplicate of #191

**Closed by kmjennison** 2021-06-27 21:21 UTC
