### ISSUE TITLE
Support setting Firebase private key only at runtime

### ISSUE THREAD

**Issue by samos123** [gladly-team/next-firebase-auth#70] opened 2021-02-13 06:36 UTC
**Describe the bug**
I'm using a Docker image to deploy my nextjs app however when I run yarn build it seems to expect the private key. This doesn't make sense for my scenario. The Firebase private key will be supplied at runtime as environment variable so it shouldn't be needed during yarn build.

See logs:
```
Step #0: [91m
Step #0: > Build error occurred
Step #0: [0m[91mFirebaseAppError: Service account object must contain a string "private_key" property.
Step #0:     at FirebaseAppError.FirebaseError [as constructor] (/build/node_modules/firebase-admin/lib/utils/error.js:44:28)
Step #0:     at FirebaseAppError.PrefixedFirebaseError [as constructor] (/build/node_modules/firebase-admin/lib/utils/error.js:90:28)
Step #0:     at new FirebaseAppError (/build/node_modules/firebase-admin/lib/utils/error.js:125:28)
Step #0:     at new ServiceAccount (/build/node_modules/firebase-admin/lib/credential/credential-internal.js:134:19)
Step #0:     at new ServiceAccountCredential (/build/node_modules/firebase-admin/lib/credential/credential-internal.js:68:15)
Step #0:     at Object.exports.cert (/build/node_modules/firebase-admin/lib/credential/credential.js:34:54)
Step #0:     at /build/node_modules/next-firebase-auth/build/index.node.js:2:16259
Step #0:     at init (/build/node_modules/next-firebase-auth/build/index.node.js:2:16290)
Step #0:     at initAuth (/build/.next/server/pages/_app.js:2976:66)
Step #0:     at Module.1TCz (/build/.next/server/pages/_app.js:416:36)
Step #0:     at __webpack_require__ (/build/.next/server/pages/_app.js:23:31)
Step #0:     at Object.0 (/build/.next/server/pages/_app.js:116:18)
Step #0:     at __webpack_require__ (/build/.next/server/pages/_app.js:23:31)
Step #0:     at /build/.next/server/pages/_app.js:91:18
Step #0:     at Object.<anonymous> (/build/.next/server/pages/_app.js:94:10)
Step #0:     at Module._compile (node:internal/modules/cjs/loader:1108:14) {
Step #0:   errorInfo: {
Step #0:     code: 'app/invalid-credential',
Step #0:     message: 'Service account object must contain a string "private_key" property.'
Step #0:   },
Step #0:   codePrefix: 'app'
Step #0: }
Step #0: [0m[91merror Command failed with exit code 1.
Step #0: [0minfo Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Step #0: The command '/bin/sh -c export COOKIE_SECRET_CURRENT=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1) &&     export COOKIE_SECRET_PREVIOUS=$COOKIE_SECRET_CURRENT &&     yarn build &&     rm -rf .next/cache' returned a non-zero code: 1
```

**Version**
Latest, ^0.12.0

Expected result:
Ability to run yarn build without having to set the private key

I followed the example application.

**Comment by samos123** [comment] 2021-02-13 08:00
Been doing some more digging and seems like one way to solve this would be to use Runtime configuration and only initialize firebase admin during server runtime? https://nextjs.org/docs/api-reference/next.config.js/runtime-configuration

**Comment by samos123** [comment] 2021-02-14 05:30
It looks like the validation is simply too strict. Maybe we could ease up the validation check such that next build won't fail the validation check when certain config is not present?

**Comment by samos123** [comment] 2021-02-14 06:09
after more digging it looks like the solution would be a bit more complex and isn't related to validation. We shouldn't init firebase admin during the `PHASE_PRODUCTION_BUILD` phase. Any chance this kind of check could be added into next-firebase-auth?

**Comment by samos123** [comment] 2021-02-14 07:06
The workaround I tried was to load the firebase admin myself however it looks like next-firebase-auth doesn't support it. I keep getting the following errors as soon as I remove the firebaseAdminConfig while running `yarn dev`:
```
error - ./node_modules/gcs-resumable-upload/node_modules/google-auth-library/build/src/auth/googleauth.js:17:0          
Module not found: Can't resolve 'child_process'                                                                                    
null                                                                                                                               
event - build page: /next/dist/pages/_error                                                                                        
wait  - compiling...
error - ./node_modules/gcs-resumable-upload/node_modules/google-auth-library/build/src/auth/googleauth.js:17:0
Module not found: Can't resolve 'child_process'
null
Error: Cannot find module '/home/samos/workspace/websu-saas/.next/build-manifest.json'
Require stack:
- /home/samos/workspace/websu-saas/node_modules/next/dist/next-server/server/load-components.js
```

**Comment by samos123** [comment] 2021-02-15 06:20
The only way I got this working was by forking next-firebase-auth and adding a check such that firebase admin won'get initialized during build time: https://github.com/samos123/next-firebase-auth/blob/main/src/initFirebaseAdminSDK.js#L5

In my Dockerfile I then run yarn build like this:
```
BUILD=true yarn build
```

Happy to provide a pull request with the added check if you feel that's acceptable. I definitely don't want to keep maintaining a fork.

**Comment by kmjennison** [comment] 2021-02-15 17:58
The error you reference in this issue is coming from Firebase, not `next-firebase-auth`, so it doesn't have to do with this package's config validation.

> The workaround I tried was to load the firebase admin myself however it looks like next-firebase-auth doesn't support it

You should be able to initialize Firebase yourself before initializing `next-firebase-auth`. See [this comment](https://github.com/gladly-team/next-firebase-auth/discussions/61#discussioncomment-323977) for an example.

> I definitely don't want to keep maintaining a fork.

I'd expect this package to work if you choose not to init Firebase admin during build.

I'm going to close this for now, but feel free to comment if you can't get things working or if you see a way to make this easier for your use case without removing config validation altogether.

**Comment by samos123** [comment] 2021-02-16 02:12
the package today won't be able to support a docker build based workflow where the environment variables are only set at runtime. I wasn't able to figure out how to not init firebase admin when it's client side. I tried the standard checking for window undefined but that would cause initAuth to fail. Note that I'm relatively a beginner with Nextjs and node in general, so maybe that's why I couldn't get it working after spending a few days on it :) so guess I will continue my fork for now.

I hope when more people have similar issues that it might become a priority. I spent a

**Comment by kmjennison** [comment] 2021-02-16 15:49
I see, thanks for explaining. If I understand correctly, the problem is you need to *avoid* initializing the Firebase admin app during build only, which isn't possible because `next-firebase-auth` will initialize it if it's not initialized already. And, if you disable initializing `next-firebase-auth` during build, the built app will error. Does that sound right?

I see two approaches:
* Only initialize Firebase admin during when it's used, not in advance. The downside here is not catching an unintentional missing credential during build.
* Add an environment variable to conditionally disable admin init, as you've done.

**Comment by samos123** [comment] 2021-02-17 08:35
Spot on. I reread the issue and see how bad a job I did at explaining. I like your 1st approach of only init Firebase admin when you really need it.

**Comment by Parnswir** [comment] 2021-02-18 10:21
Is there a chance that something like this could land in the library soon? I'd say building a single docker image for multiple environments (staging/prod) is a common use-case and currently not possible if the AdminSDK config needs to be supplied at build time.

**Closed** 2021-02-19 20:42 UTC

**Comment by kmjennison** [comment] 2021-02-19 20:48
This is available in v0.13.0-alpha.0! 🎊 Please let me know if it works for you.

**Comment by kmjennison** [comment] 2021-03-10 00:27
@samos123 @Parnswir -- Is this working well for you?

**Comment by samos123** [comment] 2021-03-14 01:53
I'm sorry I haven't had the time to switch back to upstream yet. I will let you know as soon as I switch back. Haven't had much time to work on side project recently.

**Comment by Parnswir** [comment] 2021-03-16 10:42
me neither, but it looks like nextjs@10.0.8 breaks something in our next-firebase-auth setup, so I'll probably spend some time with it anyway soon.

**Comment by harshmaur** [comment] 2021-05-19 06:15
@kmjennison Is there a documentation on how to do that? I do `initAut()` in `_app.tsx` and I am unable to build the project.

**Comment by kmjennison** [comment] 2021-05-19 18:05
@harshmaur You should be able to simply set the config as in the [documentation](https://github.com/gladly-team/next-firebase-auth#get-started) and [example app](https://github.com/gladly-team/next-firebase-auth/tree/main/example), and `next-firebase-auth` won't init Firebase admin until runtime. If you're having trouble, please open a new [discussion](https://github.com/gladly-team/next-firebase-auth/discussions).

**Comment by samos123** [comment] 2022-02-25 04:00
confirmed that it's all working for me now :D Glad I was finally able to get off my fork and use the upstream version again.

**Comment by kmjennison** [comment] 2022-02-25 20:43
Great to hear!

**Comment by nanduri1998** [comment] 2022-03-18 17:36
Hello,

I am not able to still able to do this in Docker. I have tried as specified in #444 but it seems not to be working. My Dockerfile and Config snippet are in https://github.com/gladly-team/next-firebase-auth/issues/444#issuecomment-1059903182
