### ISSUE TITLE
Support a different URL after sign out

### ISSUE THREAD

**Issue by moises-marquez** [gladly-team/next-firebase-auth#186] opened 2021-05-23 15:08 UTC
**Describe the bug**
When a custom `authPageURL` is provided via one of the HOCs, it will be used when calling `AuthUser.signout()`

**Version**
0.13.0-alpha.4

**To Reproduce**
1. Wrap your NextJS page component with any of the provided HOCs; for the sake of the example, let's use `withAuthUser`

2. Provide a custom `authPageURL` to the HOC's options: 

```
export default withAuthUser({
 ...
 authPageURL: '/another-page'
})(MyPage);
```

3. Call `AuthUser.signout()` from within that page's context.

4.  The custom authPageURL is used for the redirection after the user is succesfully logged out.

**Expected behavior**
A decoupled redirection logic after successfully logging out the user. i.e. either ignore the custom  authPageURL or use `getConfig().appPageURL`.

**Additional context**
This is half a bug and half a feature request. I looked through the code base, and didn't find a straight-forward way to tackle this issue but, if someone from the maintainers who's more knowledgeable of the code base is open to discuss possible solutions and points me to the relevant sections, I could create a PR to fix it.

So far, I've thought about either pass a parameter to the signOut function which would override the `appPageURL`, or have another property in the init config for this purpose; something like a `signOutAuthPageURL`.

**Comment by kmjennison** [comment] 2021-05-23 18:27
@moises-marquez Thanks for this issue. What you've described is currently the expected behavior: when using `AuthAction.REDIRECT_TO_LOGIN`, an unauthenticated user will cause a redirect to the login page URL.

The redirect URLs passed to the config can also be functions, a feature which is currently not well-documented: #122. See source code [here](https://github.com/gladly-team/next-firebase-auth/blob/main/src/withAuthUser.js#L122). Could you use that to conditionally route to the right page?

**Comment by moises-marquez** [comment] 2021-05-26 12:48
Hi, Kevin. I was actually passing it a function to access the context and the AuthUser, but couldn't find any way to differentiate those two scenarios:

- When a user with no session visits the given page
- When a user that was logged in, logs out when at that given page

I will give it another try and see if there's anything I could use :).

**Comment by kmjennison** [comment] 2021-05-28 22:17
Got it, makes sense. For now, you'd have to handle redirects on your own by setting the `whenUnauthedBeforeInit`/`whenUnauthedAfterInit` to `AuthAction.RENDER`. Then you can redirect yourself after calling the `signOut` method.

I'd be happy to build in support for a `signOutURL` option but I'm not sure the best way to approach it. Right now, our auth logic is triggered by `firebase.auth().onIdTokenChanged`, so this package also doesn't have a clear view of when an unauthed user was triggered by a manual signout. Similarly, using `firebase.auth().onAuthStateChanged` will fire for unauthed users on page load, too. There might be something in the Firebase JS SDK API that would help here. Any suggestions?

Relevant src files: [`withAuthUser`](https://github.com/gladly-team/next-firebase-auth/blob/main/src/withAuthUser.js), [`useFirebaseUser`](https://github.com/gladly-team/next-firebase-auth/blob/main/src/useFirebaseUser.js)

Other possible approaches:
* Assume a state change from authed --> unauthed is caused by a signout, but that's imperfect because it could happen for other reasons.
* On `signOut`, modify the AuthUser to have a field like `__signedOut`, but this would fail when a developer calls `signOut` directly on the Firebase JS SDK.

**Comment by kmjennison** [comment] 2021-05-28 22:23
Also wanted to note that this doesn't work well:
```js
await AuthUser.signOut() // this will trigger the redirect via `withAuthUser` first
window.location = '/my-next-page/'
```

**Comment by Kaosam** [comment] 2022-02-07 10:56
I confirm that if there is the option to choose a different URL for logout, it will be really appreciated

**Comment by kmjennison** [comment] 2023-12-31 20:49
Closing this as something we likely won't implement given the ability to build your own app logic to handle more customized behavior.

**Closed by kmjennison** 2023-12-31 20:49 UTC
Labels: enhancement, help wanted
