### ISSUE TITLE
Allow using withAuthUser with the _app.tsx

### ISSUE THREAD

**Issue by droganov** [gladly-team/next-firebase-auth#143] opened 2021-04-15 15:40 UTC
Not sure if that's a miss-pattern, but it looks reasonable to have the ability to only call `withAuthUser` once in the app, and make user available to all pages.

Basically, it works, but the typings not OK.

the code:
```js
const MyApp = ({ Component, pageProps }) => {
  return (
    <AuthScreen>
      <Component {...pageProps} />
    </AuthScreen>
  )
}
export default withAuthUser()(MyApp)
```

the TS error:
<img width="807" alt="image" src="https://user-images.githubusercontent.com/1375299/114897514-fb27e980-9e19-11eb-9c99-f9f341fc7453.png">

**Comment by kmjennison** [comment] 2021-04-16 01:41
Duplicate of #64. This package probably won't support this in the near future, but [here](https://github.com/gladly-team/next-firebase-auth/issues/64#issuecomment-817444118) is an example of a way to achieve what you're looking for.

**Closed by kmjennison** 2021-04-16 01:41 UTC
