### ISSUE TITLE
[Only on ios chrome] Error: The request must have an Authorization header value, or you should explicitly provide an ID token to "setAuthCookies".

### ISSUE THREAD

**Issue by luudv** [gladly-team/next-firebase-auth#523] opened 2022-08-04 08:23 UTC
**Describe the bug**
Hi, 
I have used your plugin for my app authentication. The app works fine on other browsers except chrome on iOS. I checked the log and got this error:
<img width="936" alt="2022-08-04_3-15-11 PM" src="https://user-images.githubusercontent.com/2778871/182799052-07ea6b75-9019-4942-8eb0-b751c33442d1.png">

**Versions**

`next-firebase-auth` version: 9.9.0
Firebase JS SDK: 1.0.0-canary.11
Next.js: 12.2.3

**Comment by kmjennison** [comment] 2022-08-04 21:08
Could you provide code and a live reproduction?

You should double-check that your call to setAuthCookies has an Authorization header value set to the user's ID token.

**Comment by luudv** [comment] 2022-08-06 13:37
> Could you provide code and a live reproduction?
> 
> You should double-check that your call to setAuthCookies has an Authorization header value set to the user's ID token.

Thanks for the response, I basically configured the same as your example https://github.com/gladly-team/next-firebase-auth/blob/main/example/utils/initAuth.js . Using `loginAPIEndpoint` and `logoutAPIEndpoint` and don't use `tokenChangedHandler`.  I have tested browsers on mobile and desktop. Only the chrome browser on IOS is not working, I don't know why.

**Comment by kmjennison** [comment] 2022-08-08 19:14
@luudv Have you tried the live demo of the example app? https://nfa-example.vercel.app/ It works for me on Chrome iOS.

**Comment by kmjennison** [comment] 2022-08-25 21:11
Closing until there's a clear way to reproduce.

**Closed by kmjennison** 2022-08-25 21:11 UTC
Labels: needs info/repro

**Comment by ancashoria** [comment] 2023-02-22 10:15
I'm also having this issue. You can reproduce it here: https://app.herewith.eu/sign-in (sign in with phone number on iOS / chrome)

**Comment by jodik** [comment] 2023-06-02 23:43
Same story, the demo https://nfa-example.vercel.app/  does not use 1.0.canary versions
Only affects chrome on iOS
