### ISSUE TITLE
NextJS api login getting spammed

### ISSUE THREAD

**Issue by kerubkim** [gladly-team/next-firebase-auth#715] opened 2024-06-07 17:01 UTC
**When filing a bug report, please confirm you've done the following:**

1. Have you set `onVerifyTokenError` and `onTokenRefreshError` in your config and checked for any helpful errors? Yes
2. Have you set `debug: true` in your config and read through server-side and client-side debug logs for any helpful messages? Yes
3. Have you tried the [example app](https://github.com/gladly-team/next-firebase-auth/tree/v1.x/example) with your own Firebase credentials? 
4. Have you read through the [troubleshooting](https://github.com/gladly-team/next-firebase-auth/tree/v1.x#troubleshooting) Q&A? Yes

**Describe the bug**
A clear and concise description of the bug.

As mentioned in the title `/api/login` is being requested at every refresh or redirect of page. Is this normal behavior? 

**Versions**

`next-firebase-auth` version: ^1.0.2
Firebase JS SDK (`firebase`): ^10.7.2
Firebase admin SDK (`firebase-admin`):  ^12.0.0
Next.js: 13.5.6

**To Reproduce**

**Expected behavior**

**Debug and error logs**
Please provide debug logs or errors from `onVerifyTokenError` and `onTokenRefreshError`.

**Additional context**

**Comment by kerubkim** [comment] 2024-06-07 17:13
Also seems, just by casually viewing scrolling at a page seems to make requests to the endpoint. I've added a screenshot.
<img width="1168" alt="Screenshot 2024-06-07 at 10 10 59 AM" src="https://github.com/gladly-team/next-firebase-auth/assets/28641896/3b681bcb-8f60-4a14-bef3-0f3f09a9c8bc">

**Comment by kmjennison** [comment] 2024-06-07 17:44
Thanks! I believe this is a duplicate of #424, but let me know if it differs.

**Closed as completed by kmjennison** 2024-06-07 17:44 UTC
