### ISSUE TITLE
Larger bundler size when importing next-firebase-auth than expected?

### ISSUE THREAD

**Issue by krthush** [gladly-team/next-firebase-auth#231] opened 2021-07-15 09:28 UTC
**Describe the bug**
Seems like there is some issue with bundle size, when importing next-firebase-auth, that leads to a considerably larger bundle size than expected. 

In my case "without" using import { ... } from 'next-firebase-auth'; gives a package size for firstload of a page of 75.1kb, then we usinng the imports the size jumps to 143kb - I read elsewhere you should only expect the size to be around 20kb?

**Version**
"next-firebase-auth": "^0.13.2"

**To Reproduce**
with using next-firebase-auth
[username].tsx
```
...
import initAuth from '../initAuth';
import { AuthAction, AuthUserContext, withAuthUser } from 'next-firebase-auth';
initAuth(); // Required if page uses any auth calls related to next-firebase-auth
....
export default  withAuthUser({
  whenUnauthedBeforeInit: AuthAction.RENDER,
  whenUnauthedAfterInit: AuthAction.RENDER,
})(Profile)
```

without using next-firebase-auth
[username].tsx
```
....
export default  Profile
```

**Comment by kmjennison** [comment] 2021-07-15 19:07
@krthush This package's built code is 10kb on the client side and 21kb on the server side, so that difference probably includes other dependencies—probably Firebase itself. Can you analyze the bundles before/after to see what's added?

Likely duplicate of #81.

This should be improved when #164 is implemented.

**Comment by krthush** [comment] 2021-07-15 19:54
sure, building the bundle with the next-firebase-auth import results in the following bundle:

![image](https://user-images.githubusercontent.com/33790334/125848495-818bc010-91d5-4749-97ca-3d399638dadf.png)

and for the client analyzed is:

![image](https://user-images.githubusercontent.com/33790334/125848655-398f4ed8-cd30-4f3e-9d58-ced5b9381314.png)

and the server side analyzed is:

![image](https://user-images.githubusercontent.com/33790334/125848704-3d926ce8-51a7-4fe3-a6e0-3b1bb5709867.png)

now for the instance when the import is removed (to keep things simple on my end, I only removed it for the index page, so we can pay attention to the "/" page), so this change:

![image](https://user-images.githubusercontent.com/33790334/125849150-d0aa46c1-c4b0-4777-b7cf-e0c382be886f.png)

results in the following bundle:

![image](https://user-images.githubusercontent.com/33790334/125849045-85ec7fb7-236a-417e-96c0-99d406051e35.png)

and for the client analyzed is:

![image](https://user-images.githubusercontent.com/33790334/125849205-61616f5a-5bc8-46db-a835-48073d829ae9.png)

and the server side analyzed is:

![image](https://user-images.githubusercontent.com/33790334/125849259-c39ecdf5-f71e-4558-be3a-2b216e1d2558.png)

**Comment by krthush** [comment] 2021-07-15 20:16
lol, at the very least i just noticed both headless ui and react-social-icons are bit fat :sweat_smile: so I can maybe try to dynamically import them to save around 20-40kb

apologies if a bit of an info dump and also that its not completely decoupled (its quite painstaking to remove ALL instances of next-firebase-auth from the app, so hope that this is enough to help gauge the problem)

**Comment by krthush** [comment] 2021-07-16 13:42
okay... i trying a bit of a hack? not really working, wondering if its possible to do this or if im going about it all wrong

so the page is in question is static (ISR) and publicly accessable (unauthed), its really important that this page be as tiny and as quick to access as possible, after access it does "change" slightly if the user is authed (mainly just allowing them to additional actions), but its fine if this is sideloaded as to prioritize loading the public data first

the "hack" im using to avoid having to load firebase + next-firebase-auth, is to basically create a empty auth component with the heavy imports that is **dynamically load** then auth related properties being set to a global context (so that when a user does try to do additional actions, i check the global context first to see if they are auth - i.e. check for user id / token). showing the component to add clarity:

![image](https://user-images.githubusercontent.com/33790334/125956989-ecbeb247-4d5a-40a6-9065-9a7c5dbc9430.png)

and then we load in the component dynamically into the profile page:

```
...
import dynamic from 'next/dynamic';
const GetAuthUser = dynamic(() => import("../components/GetAuthUser"));
...
const Profile = ({staticProfile, staticFavorites}: any) => {
...
 return(
   <Layout>
        ...
        <GetAuthUser/>
    </Layout>
  )
}
export default Profile
```

doesn't really work, i get an auth error when loading the page x) i'm assuming because the way auth is implemented isn't as plug and play, and you can't really check auth properly if you load stuff "thereafter"

**Comment by kmjennison** [comment] 2021-08-03 15:13
Thanks for this info. I explored this in the demo app and feel confident the bundle size is mostly Firebase JS.

First load JS for the example app index page:
* With `next-firebase-app` (NFA): 136kb
* Without NFA: ~66kb -- commit https://github.com/gladly-team/next-firebase-auth/commit/53c4eff082679439d634dd506f6d9ede9633b6c5
* Without NFA _but with Firebase_: 130kb -- commit https://github.com/gladly-team/next-firebase-auth/commit/7181cae583192ab94d32091e0ba97607d59a0a85

With NFA:
![Screen Shot 2021-08-03 at 10 50 29 AM](https://user-images.githubusercontent.com/5924325/128037308-06e17aca-7d2b-47f8-be3d-9886a4b1bf40.png)

Without NFA:
![Screen Shot 2021-08-03 at 10 48 35 AM](https://user-images.githubusercontent.com/5924325/128037254-7f2df8cd-127b-4606-89a9-953eead0c82c.png)

Without NFA but with Firebase:
![Screen Shot 2021-08-03 at 11 06 41 AM](https://user-images.githubusercontent.com/5924325/128040147-210309f0-cea5-474c-a8b7-80593ea8e4d6.png)

Firebase's size should be reduced when #164 is implemented.

**Closed by kmjennison** 2021-08-03 15:13 UTC

**Comment by krthush** [comment] 2021-08-03 15:17
Cool sounds good, yeah hopefully we'll get the modular firebase support sometime and then we can further reduce the bundle size impact from firebase.
