### ISSUE TITLE
withAuthUserTokenSSR does not have auth on Safari

### ISSUE THREAD

**Issue by dwidjaja945** [gladly-team/next-firebase-auth#452] opened 2022-03-19 09:24 UTC
**Describe the bug**
I apologize if this is a duplicate~
This issue only happens on Safari. Working as expected on Chrome and Firefox (did not test on Edge, though).

When I have a route that uses `withAuthUserTokenSSR`, it does not have the auth user, even after a successful login.
This does not change despite the configurations passed.

**Versions**

`next-firebase-auth` version: ^1.0.0-canary.5
Firebase JS SDK: ^9.6.
Next.js: latest

**To Reproduce**
I apologize for not having any live examples to share at the moment.

1. Export a `getServerSideProps` wrapped with `withAuthUserTokenSSR`.
```
export const getServerSideProps = withAuthUserTokenSSR({
      appPageURL: '/app_page',      
      whenAuthed: AuthAction.RENDER,
      whenUnauthed: AuthAction.REDIRECT_TO_LOGIN,
      authPageURL: '/some_page',
      ...options,
    })(() => {
          // ...
    });
```
2. When landing on this page **in Safari**, I am always redirected to my login page.

**Expected behavior**
I expect the behaviors between Safari and Chrome to match, where I have the auth user available in `getServerSideProps`.

**Additional context**
I tested exporting `getServerSideProps` alone without `withAuthUserTokenSSR`.
When `getServerSideProps` is not wrapped, the page in Safari loads as expected.

It is only when I wrap it with `withAuthUserTokenSSR` do I run into this issue.

Thanks in advance~

**Comment by kmjennison** [comment] 2022-04-01 16:55
It seems likely that the auth cookies are not being set, which can be due to browser settings or browser extensions.

Can you inspect the request that fires when you log in on Safari? Is the `set-cookie` response header set, and are the cookies set after that request completes?

**Comment by div-cowboy** [comment] 2022-04-26 23:23
I'm also experiencing this issue on safari. I have my app in production, and some of my users reported it. Here is a quick example.

```
export const getServerSideProps = withAuthUserTokenSSR({
  whenUnauthed: AuthAction.REDIRECT_TO_LOGIN,
  authPageURL: "/login",
})(async ({ AuthUser }) => {
  let isUserMentor = await confirmUserIsMentor();

  async function confirmUserIsMentor() {
    let isUserRole = getFirebaseAdmin()
      .auth()
      .getUser(AuthUser.id)
      .then((userRecord) => {
        let isUserRole =
          userRecord?.customClaims?.["mentor"] ||
          userRecord?.customClaims?.["admin"];
        return isUserRole;
      });

    return isUserRole;
  }

  // if (!isUserMentor) {
  //   // They aren't an admin
  //   return {
  //     redirect: {
  //       destination: `/app/dashboard`,
  //       permanent: false,
  //     },
  //   };
  // }

  return {
    props: {
      test: "test",
    },
  };
});

export default withAuthUser({
  whenUnauthedAfterInit: AuthAction.REDIRECT_TO_LOGIN,
  whenUnauthedBeforeInit: AuthAction.SHOW_LOADER,
})(MentorStudentApplications);
```

**Comment by frederikvanhevel** [comment] 2022-06-16 10:18
I'm also experiencing this issue. Have you found any solution for this?

**Comment by kamami** [comment] 2022-07-01 10:00
Same issue

**Comment by princefr** [comment] 2022-07-11 11:29
same issue

**Comment by abusada** [comment] 2022-07-12 07:03
Can you try setting cookie's `sameSite` config to ["Lax",](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite#lax)?

[This could be the issue: ](https://caniuse.com/?search=SameSite%3DLax):
![screenshot- 2022-07-12 at 09 02 37@2x](https://user-images.githubusercontent.com/2572320/178428939-7be27104-d6bd-43f9-969c-2a69308076cd.jpg)

**Comment by princefr** [comment] 2022-07-14 11:35
The problem emerge when ones set the signed parameter to true
  ```
 cookies: {
      ...,
     signed: true,
   }
```

**Comment by kmjennison** [comment] 2022-08-05 20:08
Closing this as related to cookie settings.

If you're running into this issue, verify that `secure` is only set to true in HTTPS environments, the browser and your app deployment support the SameSite setting, and that your cookie keys are set correctly when `signed` is true.

Please open a new issue with a live reproduction if you identify a problem with `next-firebase-auth`'s behavior.

**Closed by kmjennison** 2022-08-05 20:08 UTC
Labels: needs info/repro
