### ISSUE TITLE
Firebase client initialization error when using firebase 9.17.1 (latest)

### ISSUE THREAD

**Issue by joeyscarim** [gladly-team/next-firebase-auth#614] opened 2023-02-17 18:36 UTC
**When filing a bug report, please confirm you've done the following:**

1. Have you set `onVerifyTokenError` and `onTokenRefreshError` in your config and checked for any helpful errors?
Yes

2. Have you set `debug: true` in your config and read through server-side and client-side debug logs for any helpful messages?
Yes

3. Have you tried the [example app](https://github.com/gladly-team/next-firebase-auth/tree/v1.x/example) with your own Firebase credentials?
Yes, see below for how I reproduced this using the canary example

5. Have you read through the [troubleshooting](https://github.com/gladly-team/next-firebase-auth/tree/v1.x#troubleshooting) Q&A?
Yes

**Describe the bug**
When using the client side firebase as shown in the examples in the readme i.e. `getFirestore(getApp())` with the latest version of firebase 9.17.1 the error `FirebaseError: Firebase: Need to provide options, when not being deployed to hosting via source. (app/no-options).` appears.

Seems to be an initialization error because doing my own client side initialization instead, like the example here https://github.com/shadeemerhi/reddit-clone-yt/blob/main/src/firebase/clientApp.ts, works as expected.

**Versions**
`next-firebase-auth` version: 1.0.0-canary.19
Firebase JS SDK: 9.17.1
Next.js: 12.2.3 (also experienced same issue in my next@13.1.6 project)

**To Reproduce**
- Cloned the repo and added my dev firebase env variables
- Logged in
- Added an example use effect that fetches a document on the `ssr-auth-required` page:
```
import { getApp } from 'firebase/app'
import {getFirestore, doc, getDoc} from 'firebase/firestore';
```
...
```
  useEffect(() => {
    const getUser = async () => {
      const ref = doc(getFirestore(getApp()), "events/mtv/users", AuthUser.id);
      const docSnap = await getDoc(ref);
      if (docSnap.exists()) {
        console.log("Document data:", docSnap.data());
      } else {
        console.log("No such document!");
      }
    }

    getUser();
  }, []);
```
- Works as expected
- Next I updated firebase to latest, and re-ran. I now get the error: `FirebaseError: Firebase: Need to provide options, when not being deployed to hosting via source. (app/no-options).`
- Next I updated next-firebase-auth to latest canary `yarn add next-firebase-auth@1.0.0-canary.19`, but same error persists

**Expected behavior**
Expected the client to be initialized and getFirestore to work, like with previous version of firebase and in the example at https://github.com/gladly-team/next-firebase-auth#using-the-firebase-apps

**Debug and error logs**
Please provide debug logs or errors from `onVerifyTokenError` and `onTokenRefreshError`.
Not relevant

**Additional context**
Thank you for any help/explanations!

**Comment by spife129** [comment] 2023-02-22 15:04
The current version doesn't work with firebase ver > 9.*, you will have to stick with ver 8.9 at the moment. I run into similar issue where the error says firebase.apps is undefined as in ver 9 it uses getApps() but the current lib still uses firebase.apps.

**Comment by kmjennison** [comment] 2023-02-22 15:37
@spife129 That is not correct. The canary version of `next-firebase-auth` supports Firebase JS SDK v9. Please see [README](https://github.com/gladly-team/next-firebase-auth#get-started) for more info.

**Comment by kmjennison** [comment] 2023-02-22 15:39
@joeyscarim You mention that your app worked prior to upgrading Firebase to 9.17.1. What was the version of Firebase that worked? I'm wondering if this is a Firebase bug. Possibly related: #612

**Comment by spife129** [comment] 2023-02-22 15:44
> @spife129 That is not correct. The canary version of `next-firebase-auth` supports Firebase JS SDK v9. Please see [README](https://github.com/gladly-team/next-firebase-auth#get-started) for more info.

As you said, it's the canary version, are you saying we should use canary for production? It's the fact that the current version is not working with the ver 9. Please consider the use of words before you reply.

**Comment by kmjennison** [comment] 2023-02-22 16:07
@spife129 That's fair. The current canary version will likely see some API changes before v1.x (see [roadmap](https://github.com/gladly-team/next-firebase-auth/issues/265)), but it's intended to be usable in production. Of course, each developer should evaluate what makes sense for their production app.

Regardless, this issue specifically references using the canary version with latest Firebase, which should work just fine. I don't want other readers to think those are incompatible, so I'm going to hide these comments as off-topic to this issue.

**Comment by spife129** [comment] 2023-02-22 16:11
Maybe make a note at the readme section that talks about upgrading to ver 9? So it's much easier for people to understand which version works. Thanks

**Comment by joeyscarim** [comment] 2023-02-22 22:39
@kmjennison The version of firebase i was using was 9.16.0, which was working with next-firebase-auth 1.0.0-canary.18 as expected and as the examples in the docs show. the example in the repo which uses 9.9.1 works as well.

my confusion on it being a firebase bug or a next-firebase-auth bug is when i initialize firebase myself (doing it the exact same way as here: https://github.com/shadeemerhi/reddit-clone-yt/blob/main/src/firebase/clientApp.ts), prior to next-firebase-auth init, it works with the latest firebase version, 9.17.1

**Comment by kmjennison** [comment] 2023-02-23 19:26
@joeyscarim Interesting. Looking at that example, one difference is the call to `getFirestore` outside of the component render. What happens if you try that pattern?
```js
import { getApp } from 'firebase/app'
import { getFirestore } from 'firebase/firestore'

const firestore = getFirestore(getApp())

// component below or in another module
```

Possibly related StackOverflow post: https://stackoverflow.com/a/74732162/1332513

**Comment by wongww** [comment] 2023-03-02 09:11
I've been using functions like `getApp()` and `getAuth()` inside a `useEffect()` hook.

I don't know if that's a "good" of way of accessing the firebase app, but so far that's the only way I've gotten it to work. Ideally, I would like to have access to the firebase before rendering the component.

Correct me if I'm wrong @kmjennison, but it's expected that getApp() returns nothing if it's not called in a `useEffect()` hook?

**Comment by kmjennison** [comment] 2023-03-02 15:58
@wongww That isn't the behavior I'd expect based on [the docs on `getApp`](https://firebase.google.com/docs/reference/js/app#getapp):

> When called with no arguments, the default app is returned. When an app name is provided, the app corresponding to that name is returned.
>
> An exception is thrown if the app being retrieved has not yet been initialized.

**Comment by mrnguyentrantam** [comment] 2023-03-03 04:54
Hello, I encountered the same issue when using firebase 9.17 version, works well after downgrading to 9.16. Maybe firebase change the way they init internally @kmjennison

**Comment by clemenscodes** [comment] 2023-03-06 11:01
Had to downgrade to 9.16. With 9.17.1 or 9.17.2 I have to initialize Firebase myself to make this error go away, however then the tokens can't be verified and the emulators don't connect.

**Comment by mkilp** [comment] 2023-03-07 17:11
Having the same exact issue. I am on firebase 9.16.0 and "next-firebase-auth": "1.0.0-canary.18". Downgrading both does not seem to work for me at all.

**Comment by wongww** [comment] 2023-03-16 06:57
@kmjennison I've been calling functions like `getApp()` in a useEffect hook because I discovered that if I didn't, then `getApp()` would be called before the initAuth() function is finished (at least that's how I interpreted it :) ). In other words, `getApp()` was always throwing this initialization error before the component I call it in is finished mounting. Any thoughts on this flow? Would this be something you expected?

**Comment by kmjennison** [comment] 2023-03-16 15:53
@wongww I'm not sure what you're running into. You might double-check a few things:
* that you're not calling `getApp` on the server side, because it's a client SDK
* you're calling init in _app.js outside of the component

The example calls uses `getApp` outside of `useEffect` without a problem:
https://github.com/gladly-team/next-firebase-auth/blob/80e5830661bfb21e87e33fc0174abf0cf47ce4e7/example/components/FirebaseAuth.js#L45

**Comment by FabianRueckert** [comment] 2023-03-17 19:11
I am getting the same error, even if I call
```
initAuth();
export const auth = getAuth(getApp());
```
in `_app.tsx` right behind each other. 
And also when calling `getAuth(getApp())` inside a component on the client side.
Both on firebase 9.16.0 and 9.17.1.

Debug console also shows that next-firebase-auth has initialized right before.
![image](https://user-images.githubusercontent.com/61990737/226010793-310386ad-9d82-46e9-a4a4-7ef3b070d14d.png)

**Comment by mkilp** [comment] 2023-03-21 16:14
I solved my issue - i've been importing getApp() from firebase js vs from firebase-admin (which is initialized).

**Comment by martingouy** [comment] 2023-03-27 00:24
FWIW I am having the same issue. Downgrading to 9.16.0 fixed it

**Comment by ancashoria** [comment] 2023-03-29 14:33
Same here, downgrading to 9.16.0 didn't fix it

**Comment by ellisdod** [comment] 2023-03-29 23:44
I'm getting the same issue. In my case the init() function doesn't seem to be initializing a FirebaseApp instance that can be recognised by future getApp() calls. Calling getApps() within the initAuth file returns an empty array.  

Downgrading to 9.9.1 fixed it.

<img width="362" alt="Screenshot 2023-03-29 at 16 52 51" src="https://user-images.githubusercontent.com/25548563/228596413-d2af3287-bffd-402d-bde3-d81aaa29f6d2.png">

<img width="644" alt="Screenshot 2023-03-29 at 16 53 13" src="https://user-images.githubusercontent.com/25548563/228596464-5e5028e3-3114-4b7d-bde9-194af6169765.png">

**Comment by ZhuBoao** [comment] 2023-04-08 15:59
On client side, Downgrading to 9.9.1 can fix it. But I still cannot get correct response from `getApps()` or `getApp()` from server side. I am sure I called `initAuth()` on the top of the API.

**Comment by rafaeldcf** [comment] 2023-04-08 17:39
This is my workaround until a real fix. I´m using firebase 9.19.1 and next-firebase-auth 1.0.0-canary.19

Configure firebase credential in .env.local file to avoid errors duplicating data
```NEXT_PUBLIC_FIREBASE_PUBLIC_API_KEY=
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=
NEXT_PUBLIC_FIREBASE_DATABASE_URL=
NEXT_PUBLIC_FIREBASE_PROJECT_ID=
```

Add this code:
```
import { initializeApp } from "firebase/app";
```

```
const firebaseConfig = {
  apiKey: process.env.NEXT_PUBLIC_FIREBASE_PUBLIC_API_KEY,
  authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
};

try {
  const app = initializeApp(firebaseConfig);
} catch (err) {
  console.error(err);
}
```

**Comment by EvertonMJunior** [comment] 2023-04-10 02:55
> This is my workaround until a real fix. I´m using firebase 9.19.1 and next-firebase-auth 1.0.0-canary.19
> 
> Configure firebase credential in .env.local file to avoid errors duplicating data
> 
> ```
> NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=
> NEXT_PUBLIC_FIREBASE_DATABASE_URL=
> NEXT_PUBLIC_FIREBASE_PROJECT_ID=
> ```
> 
> Add this code:
> 
> ```
> import { initializeApp } from "firebase/app";
> ```
> 
> ```
> const firebaseConfig = {
>   apiKey: process.env.NEXT_PUBLIC_FIREBASE_PUBLIC_API_KEY,
>   authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
>   projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
> };
> 
> try {
>   const app = initializeApp(firebaseConfig);
> } catch (err) {
>   console.error(err);
> }
> ```

This solved it for me. I added the initialization right after the `init()` command. The issue arose to me when I upgraded to Next 13.

**Comment by cookrn** [comment] 2023-05-31 19:43
Should an issue be opened against firebase/firebase-js-sdk or does it seem like the bug might be in this package?

**Comment by kmjennison** [comment] 2023-05-31 22:42
I haven't had a chance to investigate whether this is a Firebase bug or something in this package. Help welcome!

I reproduced the problem in the example app [here](https://github.com/gladly-team/next-firebase-auth/pull/648), and in that case, it worked when pinning the Firebase client SDK to version 9.16.0.

**Comment by cookrn** [comment] 2023-06-01 12:03
When I reproduced in a project yesterday, downgrading to 9.16.0 also fixed. I was not able to see any errors in the browser console or server logs when using 9.17.x and above, which was odd.

**Comment by steebchen** [comment] 2023-06-27 16:09
Running into this just on firebase hosting/functions (with experimental web frameworks nextj support), it seems to work on vercel. Not sure if it's the same issue. Everything works on the client, but the server app doesn't get initialized.

```
# getting this just on firebase functions:
FirebaseAppError: The default Firebase app does not exist. Make sure you call initializeApp() before using any of the Firebase services
```

I am on:

```
    "firebase": "9.16.0",
    "firebase-admin": "11.8.0",
    "firebase-tools": "12.4.0",
```

**Comment by steebchen** [comment] 2023-06-27 16:18
Actually I'm also running randomly into this on vercel now 😭 

I'm using `firebase@9.16.0` so it doesn't necessarily seem to be related to this version I think?

```
errorInfo: {
    code: 'app/no-app',
    message: 'The default Firebase app does not exist. Make sure you call initializeApp() before using any of the Firebase services.'
  },
```

**Comment by kmjennison** [comment] 2023-07-09 14:45
This appears to be fixed in firebase ^9.18.0 and 10.0.0. Let me know if you run into the issue again after upgrading!

**Comment by kmjennison** [comment] 2023-07-09 14:51
Never mind: these versions worked in development but not after building.

**Comment by kmjennison** [comment] 2023-07-09 21:43
Here's the diff in the Firebase JS SDK between the working and broken versions:
https://github.com/firebase/firebase-js-sdk/compare/firebase@9.16.0..firebase@9.17.0

**Comment by kmjennison** [comment] 2023-07-09 21:45
Possible areas of interest:
* Where the error is thrown: https://github.com/firebase/firebase-js-sdk/blob/87c03a4e9105ab0ead8b895f740f218a8b5d564c/packages/app/src/api.ts#L146
* Where Firebase might be calling `initializeApp` without any options: https://github.com/firebase/firebase-js-sdk/blob/b58a617f007a4ea2ffe82bc5b9c8ca9a7b7853d9/packages/app/src/api.ts#L204-L207

**Comment by kmjennison** [comment] 2023-07-22 17:21
Possibly related? This might be affecting our Webpack bundle / `webpack-node-externals`.

Issue:
https://github.com/firebase/firebase-js-sdk/issues/7005

Fix:
https://github.com/firebase/firebase-js-sdk/pull/7007

**Comment by Mrjuanblack** [comment] 2023-11-15 17:07
@steebchen Were you able to find a workaround? I'm also using firebase functions but I ran into the same issue as you.

**Comment by steebchen** [comment] 2023-11-16 06:21
Not really, I stayed on 9.16.0 on Vercel, which seems to work fine (on firebase hosting I run into different issue)

**Closed as completed** 2023-12-31 20:22 UTC
Labels: bug, help wanted

**Comment by kmjennison** [comment] 2023-12-31 20:23
I've updated the docs and example app to recommend initializing the Firebase JS SDK in your app prior to initializing `next-firebase-auth`, which avoids this issue.
