### ISSUE TITLE
Client-side redirects for authPageURL not matching server-side redirects when basePath is set

### ISSUE THREAD

**Issue by hershmire** [gladly-team/next-firebase-auth#176] opened 2021-05-14 19:47 UTC
**Describe the bug**
If your NextJS app has a `basePath` set, the client-side redirecting for an unauthenticated user will use the basePath while the server-side redirect will not.

**Version**
0.13.1-alpha.2

**To Reproduce**
1. Pull down Next Firebase Auth example site (https://github.com/gladly-team/next-firebase-auth/tree/main/example)
2. Add a base path to `next.config.js` i.e. `basePath: '/admin',`
3. Start application and try navigating to the different example pages
4. SSR pages will redirect without base path whereas CSR pages will include the base path

**Expected behavior**
Expect client-side and server-side auth redirects to function the same when the application has `basePath` set. Ideally, client-side redirecting can function how the server-side is currently today so we can take into account an additional use case mentioned in the additional content section.

**Additional context**
Additionally, client-side redirection should support redirecting to a URL outside of the path context of the NextJS application. This is necessary if you have multiple NextJS apps that live under the same domain (managed by a load balancer) but you only want to maintain one login page.

Example:

**App 1:**
https://example.com/admin
Basepath: `/admin`

If unauthenticated should be able to redirect to App 2's login page

**App 2:**
https://example.com/auth
Basepath: `/auth`
Login page: `/auth/login`

**Comment by kmjennison** [comment] 2021-05-14 23:07
Thanks for the detailed issue.

I can't reproduce this. [Here are the changes](https://github.com/gladly-team/next-firebase-auth/commit/aaa85ca1781639dc997d4cee988f67244e8b955c) I made to the example app to add a base path. If I visit the following SSR and static pages as an unauthed user
`http://localhost:3000/thing/ssr-auth-required`
`http://localhost:3000/thing/static-auth-required-loader`

they both redirect to `http://localhost:3000/thing/auth`, as expected.

Am I missing something?

**Comment by kmjennison** [comment] 2021-05-14 23:10
I also want to call out that:
* the redirect URLs passed to the config can also be functions, a feature which is currently not well-documented: #122 
* as far as I know, absolute URLs should work too

**Comment by kmjennison** [comment] 2021-05-24 17:51
Closing until there's a reproduction.

**Closed by kmjennison** 2021-05-24 17:51 UTC
Labels: needs info/repro

**Comment by hershmire** [comment] 2021-05-24 23:40
Apologies for the slow response @kmjennison. I'm also not able to reproduce the default behavior now. I believe the confusion for me was with the custom SSR routing where I modified the return `redirect` object like:

```js
redirect: {
  destination: '/login',
  permanent: false,
  basePath: false, // Option to tell Next.js to redirect without using the basePath
},
```

That's what lead me to my comment in the "Additional content" section. That is still a valid request but since it's a bit unrelated to the original issue here, I'll create a new issue that is more clear. Thanks for taking a look!
